# Microsoft Visual C++ generated build script - Do not modify

PROJ = CHARSTAK
DEBUG = 1
PROGTYPE = 3
CALLER = 
ARGS = 
DLLS = 
D_RCDEFINES = -d_DEBUG
R_RCDEFINES = -dNDEBUG
ORIGIN = MSVC
ORIGIN_VER = 1.00
PROJPATH = C:\DEV16\CHARSTAK\
USEMFC = 0
CC = cl
CPP = cl
CXX = cl
CCREATEPCHFLAG = 
CPPCREATEPCHFLAG = 
CUSEPCHFLAG = 
CPPUSEPCHFLAG = 
FIRSTC =             
FIRSTCPP = CHARSTAK.CPP
RC = rc
CFLAGS_D_WTTY = /nologo /G2 /Mq /W4 /Zi /AL /Od /D "_DEBUG" /FR /Fd"CHARSTAK.PDB"
CFLAGS_R_WTTY = /nologo /Gs /G2 /Mq /W3 /AM /Ox /D "NDEBUG" /FR 
LFLAGS_D_WTTY = /NOLOGO /ONERROR:NOEXE /NOD /PACKC:57344 /CO /ALIGN:16
LFLAGS_R_WTTY = /NOLOGO /ONERROR:NOEXE /NOD /PACKC:57344 /ALIGN:16
LIBS_D_WTTY = oldnames libw llibcewq
LIBS_R_WTTY = oldnames libw mlibcewq
RCFLAGS = /nologo
RESFLAGS = /nologo
RUNFLAGS = 
OBJS_EXT = 
LIBS_EXT = 
!if "$(DEBUG)" == "1"
CFLAGS = $(CFLAGS_D_WTTY)
LFLAGS = $(LFLAGS_D_WTTY)
LIBS = $(LIBS_D_WTTY)
MAPFILE = nul
RCDEFINES = $(D_RCDEFINES)
DEFFILE=C:\DEV16\MSVC\BIN\CL.DEF
!else
CFLAGS = $(CFLAGS_R_WTTY)
LFLAGS = $(LFLAGS_R_WTTY)
LIBS = $(LIBS_R_WTTY)
MAPFILE = nul
RCDEFINES = $(R_RCDEFINES)
DEFFILE=C:\DEV16\MSVC\BIN\CL.DEF
!endif
!if [if exist MSVC.BND del MSVC.BND]
!endif
SBRS = CHARSTAK.SBR \
		TEST.SBR \
		LOADSTAK.SBR


CHARSTAK_DEP = c:\dev16\charstak\charstak.h


TEST_DEP = c:\dev16\charstak\charstak.h \
	c:\dev16\charstak\loadstak.h


LOADSTAK_DEP = c:\dev16\charstak\loadstak.h


all:	$(PROJ).EXE $(PROJ).BSC

CHARSTAK.OBJ:	CHARSTAK.CPP $(CHARSTAK_DEP)
	$(CPP) $(CFLAGS) $(CPPCREATEPCHFLAG) /c CHARSTAK.CPP

TEST.OBJ:	TEST.CPP $(TEST_DEP)
	$(CPP) $(CFLAGS) $(CPPUSEPCHFLAG) /c TEST.CPP

LOADSTAK.OBJ:	LOADSTAK.CPP $(LOADSTAK_DEP)
	$(CPP) $(CFLAGS) $(CPPUSEPCHFLAG) /c LOADSTAK.CPP


$(PROJ).EXE::	CHARSTAK.OBJ TEST.OBJ LOADSTAK.OBJ $(OBJS_EXT) $(DEFFILE)
	echo >NUL @<<$(PROJ).CRF
CHARSTAK.OBJ +
TEST.OBJ +
LOADSTAK.OBJ +
$(OBJS_EXT)
$(PROJ).EXE
$(MAPFILE)
c:\dev16\msvc\lib\+
$(LIBS)
$(DEFFILE);
<<
	link $(LFLAGS) @$(PROJ).CRF
	$(RC) $(RESFLAGS) $@


run: $(PROJ).EXE
	$(PROJ) $(RUNFLAGS)


$(PROJ).BSC: $(SBRS)
	bscmake @<<
/o$@ $(SBRS)
<<
