SET BLASTER=A220 I7 D1 T2
SET SNDSCAPE=C:\WINDOWS
Set Path c:\;c:\bin;c:\brief;

subst d: c:\testing

rem *** Visual Cafe dbDEsettings ***
SET CLASSPATH=.;C:\VisualCafedbDE\BIN\COMPONENTS\SYMBEANS.JAR;C:\VisualCafedbDE\BIN\COMPONENTS\DATABIND.JAR;C:\VisualCafedbDE\JAVA\LIB\CLASSES.ZIP;C:\VisualCafedbDE\JAVA\LIB;C:\VisualCafedbDE\BIN\COMPONENTS\DBAW_AWT.JAR;C:\VisualCafedbDE\JAVA\LIB\DBAW.ZIP;%CLASSPATH%
SET PATH=%PATH%;C:\VisualCafedbDE\BIN;C:\VisualCafedbDE\JAVA\BIN
rem *** End Visual Cafe dbDEsettings ***

